Repository enjin/platform-core, pull requests merged in 2023-07, with the labels that each got.

#11 Update rebing
  composer.json
Labels: enhancement

#12 Remove trailing slash
  src/Http/Controllers/PlatformController.php
Labels: enhancement

#10 Support dynamic daemon address
  database/factories/EventFactory.php
  database/factories/TransactionFactory.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/OperatorTransferTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SimpleTransferTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/TransferAllBalanceMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/TransferBalanceMutation.php
  src/Rules/DaemonProhibited.php
  src/Rules/IsCollectionOwner.php
  src/Rules/IsCollectionOwnerOrApproved.php
  src/Rules/IsManagedWallet.php
  src/Support/Account.php
  src/Support/SS58Address.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchSetAttributeTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/DestroyCollectionTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Mutations/MintTokenTest.php
  tests/Feature/GraphQL/Mutations/MutateCollectionTest.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/ThawTest.php
  tests/Feature/GraphQL/Mutations/TransferAllBalanceTest.php
  tests/Feature/GraphQL/Mutations/TransferBalanceTest.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
  tests/Feature/GraphQL/Queries/GetTransactionTest.php
  tests/Feature/GraphQL/Queries/GetTransactionsTest.php
  tests/Unit/AddressTest.php
Labels: enhancement

#13 Upgrade laravel-graphiql & remove fork
  composer.json
Labels: dependencies

#14 Update cache key
  src/CoreServiceProvider.php
  src/Enums/Global/PlatformCache.php
  src/GraphQL/Schemas/Primary/Mutations/VerifyAccountMutation.php
Labels: enhancement

#15 Fixes tests badge
  README.md
Labels: documentation

#16 Fixes AsyncWebsocket + Remove deprecated networks
  .github/workflows/run_tests.yml
  composer.json
  config/enjin-platform.php
  database/factories/CollectionFactory.php
  database/factories/WalletFactory.php
  phpunit.xml
  src/Clients/Implementations/AsyncWebsocket.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Support/Metadata.php
  testbench.yaml
  tests/Feature/GraphQL/Queries/GetWalletsTest.php
  tests/TestCase.php
  tests/Unit/AddressTest.php
Labels: bug, enhancement

#17 Limit event data
  src/Events/Substrate/MultiTokens/TokenMinted.php
  src/Events/Substrate/MultiTokens/TokenTransferred.php
Labels: bug

#19 Increase test coverage
  phpunit.xml
  src/Http/Controllers/PlatformController.php
  src/Services/Auth/AuthManager.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Serialization/Implementations/Substrate.php
  src/Services/Serialization/Interfaces/SerializationServiceInterface.php
  tests/Feature/Controllers/GraphQLControllerTest.php
  tests/Feature/Controllers/PlatformControllerTest.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchSetAttributeTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/DestroyCollectionTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Mutations/MintTokenTest.php
  tests/Feature/GraphQL/Mutations/MutateCollectionTest.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/ThawTest.php
  tests/Feature/GraphQL/Mutations/TransferAllBalanceTest.php
  tests/Feature/GraphQL/Mutations/TransferBalanceTest.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
  tests/Feature/GraphQL/Resources/ApproveCollection.graphql
  tests/Feature/GraphQL/Resources/ApproveToken.graphql
  tests/Feature/GraphQL/Resources/BatchMint.graphql
  tests/Feature/GraphQL/Resources/BatchSetAttribute.graphql
  tests/Feature/GraphQL/Resources/BatchTransfer.graphql
  tests/Feature/GraphQL/Resources/Burn.graphql
  tests/Feature/GraphQL/Resources/CreateCollection.graphql
  tests/Feature/GraphQL/Resources/CreateToken.graphql
  tests/Feature/GraphQL/Resources/DestroyCollection.graphql
  tests/Feature/GraphQL/Resources/Freeze.graphql
  tests/Feature/GraphQL/Resources/MintToken.graphql
  tests/Feature/GraphQL/Resources/MutateCollection.graphql
  tests/Feature/GraphQL/Resources/MutateToken.graphql
  tests/Feature/GraphQL/Resources/OperatorTransferToken.graphql
  tests/Feature/GraphQL/Resources/RemoveAllAttributes.graphql
  tests/Feature/GraphQL/Resources/RemoveCollectionAttribute.graphql
  tests/Feature/GraphQL/Resources/RemoveTokenAttribute.graphql
  tests/Feature/GraphQL/Resources/SetTokenAttribute.graphql
  tests/Feature/GraphQL/Resources/SimpleTransferToken.graphql
  tests/Feature/GraphQL/Resources/Thaw.graphql
  tests/Feature/GraphQL/Resources/TransferAllBalance.graphql
  tests/Feature/GraphQL/Resources/TransferBalance.graphql
  tests/Feature/GraphQL/Resources/UnapproveCollection.graphql
  tests/Feature/GraphQL/Resources/UnapproveToken.graphql
  tests/Unit/AuthServiceTest.php
  tests/Unit/SerializationTest.php
Labels: enhancement

#20 Add support to espr messages
  src/Services/Database/VerificationService.php
  tests/Feature/GraphQL/Mutations/VerifyAccountTest.php
  tests/Feature/GraphQL/Queries/RequestAccountTest.php
Labels: enhancement

#21 Update requirements
  README.md
Labels: documentation

#23 Change RequestAccount flow
  src/GraphQL/Schemas/Primary/Queries/RequestAccountQuery.php
  src/Services/Database/VerificationService.php
  tests/Feature/GraphQL/Mutations/VerifyAccountTest.php
  tests/Feature/GraphQL/Queries/RequestAccountTest.php
  tests/Feature/GraphQL/Resources/RequestAccount.graphql
Labels: enhancement

#24 Fix wallet address
  src/Models/Laravel/Wallet.php
Labels: bug

#22 Update input validation
  src/GraphQL/Schemas/Primary/Mutations/UpdateTransactionMutation.php
  src/Rules/ImmutableTransaction.php
  tests/Feature/GraphQL/Mutations/UpdateTransactionTest.php
Labels: enhancement

#30 Make pruneable pending events
  config/enjin-platform.php
  database/factories/PendingEventFactory.php
  phpunit.xml
  src/Models/Laravel/PendingEvent.php
  tests/Feature/Commands/PruneTest.php
Labels: enhancement

#32 Add update account to UpdateTransaction
  src/GraphQL/Schemas/Primary/Mutations/UpdateTransactionMutation.php
  tests/Feature/GraphQL/Mutations/UpdateTransactionTest.php
  tests/Feature/GraphQL/Resources/UpdateTransaction.graphql
  tests/Unit/AddressTest.php
Labels: enhancement
