Repository enjin/platform-core, pull requests merged in 2023-11, with the labels that each got.

#49 Add PR agent
  .github/workflows/pr_agent.yml
Labels: enhancement

#79 Allow Transactions with Null Wallets
  database/factories/TransactionFactory.php
  database/migrations/2023_11_06_133605_make_account_nullable_in_transactions.php
  src/CoreServiceProvider.php
  src/Events/Global/TransactionCreated.php
  src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
  src/GraphQL/Types/Input/Substrate/Traits/HasSigningAccountField.php
  src/Services/Database/TransactionService.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchSetAttributeTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/DestroyCollectionTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Mutations/MarkAndListPendingTransactionsTest.php
  tests/Feature/GraphQL/Mutations/MintTokenTest.php
  tests/Feature/GraphQL/Mutations/MutateCollectionTest.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/ThawTest.php
  tests/Feature/GraphQL/Mutations/TransferAllBalanceTest.php
  tests/Feature/GraphQL/Mutations/TransferBalanceTest.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
  tests/Feature/GraphQL/Queries/GetTransactionTest.php
  tests/Feature/GraphQL/Queries/GetTransactionsTest.php
Labels: enhancement, Refactoring

#81 Fixes event broadcast issue
  src/Events/Global/TransactionCreated.php
  src/Events/Global/TransactionUpdated.php
Labels: bug

#83 Adds v1.1.0 to release
  database/factories/TransactionFactory.php
  database/migrations/2023_11_06_133605_make_account_nullable_in_transactions.php
  src/CoreServiceProvider.php
  src/Events/Global/TransactionCreated.php
  src/Events/Global/TransactionUpdated.php
  src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
  src/GraphQL/Types/Input/Substrate/Traits/HasSigningAccountField.php
  src/Services/Database/TransactionService.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchSetAttributeTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/DestroyCollectionTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Mutations/MarkAndListPendingTransactionsTest.php
  tests/Feature/GraphQL/Mutations/MintTokenTest.php
  tests/Feature/GraphQL/Mutations/MutateCollectionTest.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/ThawTest.php
  tests/Feature/GraphQL/Mutations/TransferAllBalanceTest.php
  tests/Feature/GraphQL/Mutations/TransferBalanceTest.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
  tests/Feature/GraphQL/Queries/GetTransactionTest.php
  tests/Feature/GraphQL/Queries/GetTransactionsTest.php
Labels: dependencies

#87 [PLA-1426] Add reserved & unreserved events to multitokens
  src/Enums/Substrate/MultiTokensEventType.php
  src/Events/Substrate/MultiTokens/TokenReserved.php
  src/Events/Substrate/MultiTokens/TokenUnreserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Unreserved.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenBurned.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Transferred.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Unreserved.php
Labels: bug

#88 [PLA-1432] Add selectable false to signingPayload
  src/GraphQL/Types/Substrate/TransactionType.php
Labels: bug

#91 [Hotfix] Fixes signingPayload on release
  src/GraphQL/Types/Substrate/TransactionType.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
Labels: bug

#92 [PLA-1426] Fixes issues with unserved&reserved
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Unreserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Unreserved.php
Labels: bug

#94 [PLA-1439] Skip if a transaction has no signer
  src/Services/Processor/Substrate/ExtrinsicProcessor.php
Labels: bug

#95 [PLA-1431] Fix parsing operation name
  src/GraphQL/Schemas/Traits/HasAuthorizableFields.php
Labels: bug

#96 [PLA-1444] Add proofCode & proofUrl
  src/GraphQL/Schemas/Primary/Queries/RequestAccountQuery.php
  src/GraphQL/Types/Global/AccountRequestType.php
  src/Services/Database/VerificationService.php
Labels: enhancement

#97 [PLA-1451] Return array instead of bool
  src/GraphQL/Schemas/Traits/HasAuthorizableFields.php
Labels: bug

#99 [PLA-1459] Add totalReceived to FuelTankAccountStorage
  .github/workflows/pr_agent.yml
  src/Services/Processor/Substrate/Codec/Types/FuelTankAccountStorage.json
Labels: enhancement

#102 [PLA-1466] Fix FreezeStateMutated event
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FreezeStateMutated.php
Labels: bug
