Repository enjin/platform-core, pull requests merged in 2023-08, with the labels that each got.

#33 Computes mintDeposit instead of saving it
  database/factories/TokenFactory.php
  database/migrations/2023_08_01_175612_remove_mint_deposit_from_tokens_table.php
  src/GraphQL/Types/Substrate/TokenType.php
  src/Models/Laravel/Token.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
  src/Services/Processor/Substrate/Parser.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
  tests/Feature/GraphQL/Queries/GetTokensTest.php
Labels: enhancement

#35 Fix unit test failing
  tests/Feature/Commands/PruneTest.php
Labels: bug

#34 Adds freezeState to CreateToken and Freeze
  src/GraphQL/Enums/FreezeStateTypeEnum.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/FreezeMutation.php
  src/GraphQL/Types/Input/Substrate/CreateTokenParamsInputType.php
  src/Models/Substrate/CreateTokenParams.php
  src/Models/Substrate/FreezeTypeParams.php
  src/Models/Substrate/MintParams.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/CanaryBatchMint.json
  src/Services/Processor/Substrate/Codec/Types/CanaryFreeze.json
  src/Services/Processor/Substrate/Codec/Types/CanaryMint.json
  src/Services/Processor/Substrate/Codec/Types/CanaryThaw.json
  src/Services/Processor/Substrate/Codec/Types/CanaryTokenAccountsStorage.json
  src/Services/Processor/Substrate/Codec/Types/CanaryTokenStorage.json
  src/Services/Processor/Substrate/Codec/Types/Freeze.json
  src/Services/Processor/Substrate/Codec/Types/Mint.json
  src/Services/Processor/Substrate/Codec/Types/TokenAccountsStorage.json
  src/Services/Processor/Substrate/Codec/Types/TokenStorage.json
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Resources/Freeze.graphql
  tests/Unit/DecodingTest.php
  tests/Unit/EncodingTest.php
Labels: enhancement

#36 Fix translation
  lang/en/input_type.php
Labels: bug

#40 Update dependencies
  composer.json
Labels: dependencies

#41 Improve test performance
  .github/workflows/run_tests.yml
  database/schema/mysql-schema.sql
  phpunit.xml
  tests/Feature/Commands/PruneTest.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/MarkAndListPendingTransactionsTest.php
  tests/Feature/GraphQL/TestCaseGraphQL.php
  tests/TestCase.php
Labels: enhancement

#45 Use db port from config
  tests/Feature/GraphQL/TestCaseGraphQL.php
  tests/TestCase.php
Labels: enhancement

#48 Fix db path
  .github/workflows/run_tests.yml
  tests/Feature/GraphQL/TestCaseGraphQL.php
  tests/TestCase.php
Labels: enhancement

#50 Update minimum amount validation
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
Labels: bug
