Repository enjin/platform-core, pull requests merged in 2024-07, with the labels that each got.

#194 [PLA-1837] Add account owner validation
  src/Rules/IsCollectionOwner.php
  src/Rules/IsCollectionOwnerOrApproved.php
  src/Support/Account.php
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#193 [PLA-1873] Make sync work with both matrix versions
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Types/CollectionStorage.json
  src/Services/Processor/Substrate/Codec/Types/TokenAccountsStorage.json
  src/Services/Processor/Substrate/Codec/Types/TokenStorage.json
  src/Services/Processor/Substrate/Parser.php
  src/Support/helpers.php
Labels: enhancement, Review effort [1-5]: 3, other

#197 [PLA-1877] Makes mutations compatible with v1010
  composer.json
  src/Clients/Implementations/SubstrateWebsocket.php
  src/Enums/Global/PlatformCache.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchSetAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/CreateCollectionMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/CreateTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/MutateTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/OperatorTransferTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetCollectionAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetTokenAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SimpleTransferTokenMutation.php
  src/GraphQL/Types/Input/Substrate/OperatorTransferParamsInputType.php
  src/GraphQL/Types/Input/Substrate/SimpleTransferParamsInputType.php
  src/Models/Substrate/BurnParams.php
  src/Models/Substrate/CreateTokenParams.php
  src/Models/Substrate/MintPolicyParams.php
  src/Models/Substrate/OperatorTransferParams.php
  src/Models/Substrate/SimpleTransferParams.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/BatchMint.json
  src/Services/Processor/Substrate/Codec/Types/BatchSetAttribute.json
  src/Services/Processor/Substrate/Codec/Types/BatchTransfer.json
  src/Services/Processor/Substrate/Codec/Types/Burn.json
  src/Services/Processor/Substrate/Codec/Types/CreateCollection.json
  src/Services/Processor/Substrate/Codec/Types/Mint.json
  src/Services/Processor/Substrate/Codec/Types/MutateToken.json
  src/Services/Processor/Substrate/Codec/Types/SetAttribute.json
  src/Services/Processor/Substrate/Codec/Types/Transfer.json
  src/Support/helpers.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#198 [PLA-1878] Marketplace mutations support to v1010
  composer.json
  src/Services/Processor/Substrate/Codec/Types/CreateListing.json
Labels: enhancement, Review effort [1-5]: 2

#199 [PLA-1879] FT mutation support for v1010
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json
  src/Services/Processor/Substrate/Codec/Types/Dispatch.json
  src/Services/Processor/Substrate/Codec/Types/DispatchAndTouch.json
  src/Services/Processor/Substrate/Codec/Types/InsertRuleSet.json
  src/Services/Processor/Substrate/Codec/Types/MutateFuelTank.json
  src/Services/Processor/Substrate/Codec/Types/RemoveAccountRuleData.json
  src/Services/Serialization/Implementations/Substrate.php
  src/Services/Serialization/Interfaces/SerializationServiceInterface.php
Labels: enhancement, Review effort [1-5]: 4

#203 [PLA-1885] Relay-watcher changes
  src/Commands/RelayWatcher.php
  src/Events/Substrate/Balances/Teleport.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#205 [PLA-1886] Improvement transaction-checker
  src/Commands/TransactionChecker.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenMutated.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#206 [Hotfix] Fixes tokenMutated
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
Labels: Review effort [1-5]: 2, Bug fix

#209 [PLA-1904] Fix GetTokens query pagination
  src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokensQuery.php
  src/Models/Laravel/Token.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  tests/Feature/GraphQL/Queries/GetTokensTest.php
Labels: bug, enhancement, Review effort [1-5]: 3, Bug fix

#211 [PLA-1910] Fixes ListingCreated event
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCreated.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#208 [PLA-1897] Fix setAttribute callIndex
  src/Services/Processor/Substrate/Codec/Encoder.php
  tests/Unit/EncodingTest.php
Labels: bug, Review effort [1-5]: 1, Bug fix

#212 [PLA-1912] Add support for new signingPayload
  config/enjin-platform.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Encoder.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#213 [PLA-1914] Fixes teleport event
  src/Events/Substrate/Balances/Teleport.php
Labels: Review effort [1-5]: 2, Bug fix

#214 [PLA-1915] Fixes MintParams
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
  src/Models/Substrate/MintParams.php
Labels: Review effort [1-5]: 2, Bug fix

#217 [PLA-1919] Make sure data is an array
  src/Support/Account.php
Labels: Review effort [1-5]: 2, Bug fix
