Repository enjin/platform-core, pull requests merged in 2024-10, with the labels that each got.

#258 [PLA-2018] Upgrade collections to new format
  database/factories/CollectionFactory.php
  database/migrations/2024_09_27_143601_upgrade_collections_table.php
  lang/en/deprecated.php
  lang/en/input_type.php
  lang/en/type.php
  src/CoreServiceProvider.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/CreateCollectionMutation.php
  src/GraphQL/Types/Input/Substrate/MintPolicyInputType.php
  src/GraphQL/Types/Substrate/CollectionType.php
  src/GraphQL/Types/Substrate/CreationDepositType.php
  src/Models/Laravel/Collection.php
  src/Models/Laravel/Traits/Collection.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/CollectionStorage.json
  src/Services/Processor/Substrate/Parser.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Queries/GetCollectionTest.php
  tests/Feature/GraphQL/Queries/GetCollectionsTest.php
  tests/Feature/GraphQL/Queries/GetWalletTest.php
  tests/Feature/GraphQL/Resources/CreateCollection.graphql
  tests/Feature/GraphQL/Resources/GetCollection.graphql
  tests/Feature/GraphQL/Resources/GetCollections.graphql
  tests/Feature/GraphQL/Resources/GetWallet.graphql
  tests/Feature/GraphQL/Resources/GetWallets.graphql
  tests/Unit/EncodingTest.php
  tests/Unit/StorageTest.php
Labels: enhancement, tests, Review effort [1-5]: 3

#259 [PLA-2019] Adds token struct to TokenType
  database/migrations/2024_09_17_164605_upgrade_tokens_table.php
  lang/en/type.php
  src/Commands/Sync.php
  src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokenQuery.php
  src/GraphQL/Types/Input/Substrate/CreateTokenParamsInputType.php
  src/GraphQL/Types/Input/Substrate/TokenMetadataInputType.php
  src/GraphQL/Types/Substrate/CreationDepositType.php
  src/GraphQL/Types/Substrate/TokenMetadataType.php
  src/GraphQL/Types/Substrate/TokenType.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  src/Models/Laravel/Traits/Token.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Types/TokenStorage.json
  src/Services/Processor/Substrate/Parser.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
  tests/Feature/GraphQL/Queries/GetTokensTest.php
  tests/Feature/GraphQL/Queries/GetWalletTest.php
  tests/Feature/GraphQL/Resources/GetToken.graphql
  tests/Feature/GraphQL/Resources/GetTokens.graphql
  tests/Feature/GraphQL/Resources/GetWallet.graphql
  tests/Feature/GraphQL/Resources/GetWallets.graphql
Labels: enhancement, tests, Review effort [1-5]: 4

#262 [PLA-2029] Ingest changes for v2.0.0 & remove async from platform:sync
  src/Commands/Sync.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/BalanceSet.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Deposit.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/DustLost.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Endowed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/ReserveRepatriated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Reserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Slashed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Transfer.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Unreserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Withdraw.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Event.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/AccountAdded.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/AccountRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/AccountRuleDataRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/CallDispatched.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/ConsumptionSet.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FreezeStateMutated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankDestroyed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankMutated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/RuleSetInserted.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/RuleSetRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferAnswered.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferPlaced.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ExpiredListingRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingConverted.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingFilled.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ProtocolFeeSet.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Approved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/AttributeRemoved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/AttributeSet.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Burned.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionAccountCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionAccountDestroyed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionDestroyed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionMutated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionTransferred.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Frozen.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Minted.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Thawed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenAccountCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenAccountDestroyed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenDestroyed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Transferred.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Unapproved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Unreserved.php
  tests/Feature/GraphQL/Mutations/AcknowledgeEventsTest.php
  tests/Feature/GraphQL/Queries/GetPendingEventsTest.php
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#263 [PLA-2033] Removes old codecs from encoder
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchSetAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/MutateTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/OperatorTransferTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetCollectionAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetTokenAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SimpleTransferTokenMutation.php
  src/Models/Substrate/BurnParams.php
  src/Models/Substrate/OperatorTransferParams.php
  src/Models/Substrate/SimpleTransferParams.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/BatchSetAttribute.json
  src/Services/Processor/Substrate/Codec/Types/BatchTransfer.json
  src/Services/Processor/Substrate/Codec/Types/Burn.json
  src/Services/Processor/Substrate/Codec/Types/CreateListing.json
  src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
  src/Services/Processor/Substrate/Codec/Types/MutateToken.json
  src/Services/Processor/Substrate/Codec/Types/SetAttribute.json
  src/Services/Processor/Substrate/Codec/Types/TokenAccountsStorage.json
  src/Services/Processor/Substrate/Codec/Types/Transfer.json
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Unit/DecodingTest.php
  tests/Unit/EncodingTest.php
Labels: enhancement, Review effort [1-5]: 3

#264 [PLA-2033] Add AuctionData back
  src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
Labels: enhancement, Review effort [1-5]: 1

#267 [PLA-2009] Add index to syncables
  database/migrations/2024_10_14_041141_add_index_to_syncables_table.php
  src/CoreServiceProvider.php
Labels: enhancement, Review effort [1-5]: 2

#266 [PLA-2036] Change force_single_mint to force_collapsing_supply.
  composer.json
  phpunit.xml
  src/Models/Laravel/Token.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Parser.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#269 [PLA-2038] Changes for supporting FuelTanks v2.0.0
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankMutated.php
  src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json
  src/Services/Processor/Substrate/Codec/Types/Dispatch.json
  src/Services/Processor/Substrate/Codec/Types/DispatchAndTouch.json
  src/Services/Processor/Substrate/Codec/Types/FuelTankAccountStorage.json
  src/Services/Processor/Substrate/Codec/Types/InsertRuleSet.json
  src/Services/Processor/Substrate/Codec/Types/MutateFuelTank.json
  src/Services/Processor/Substrate/Codec/Types/TankStorage.json
  src/Services/Processor/Substrate/Events/SubstrateEvent.php
Labels: enhancement, Review effort [1-5]: 3

#260 [PLA-2023] Improve metadata caching
  config/enjin-platform.php
  lang/en/error.php
  lang/en/mutation.php
  src/Commands/SyncMetadata.php
  src/CoreServiceProvider.php
  src/Enums/Global/PlatformCache.php
  src/Events/Substrate/MultiTokens/MetadataUpdated.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/RefreshMetadataMutation.php
  src/Jobs/SyncMetadata.php
  src/Models/Laravel/Attribute.php
  src/Models/Laravel/Token.php
  src/Services/Database/MetadataService.php
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#271 [PLA-2023] Fix error logging
  src/Jobs/SyncMetadata.php
  src/Models/Laravel/Attribute.php
Labels: bug, Review effort [1-5]: 1, Bug fix

#270 [PLA-2041] Adds ListingRemovedUnderMinimum & canary v1013 runtime
  config/enjin-platform.php
  config/enjin-runtime.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingRemovedUnderMinimum.php
Labels: enhancement, Review effort [1-5]: 2, other

#272 [PLA-2043] Use stable packages
  composer.json
Labels: enhancement, dependencies, Review effort [1-5]: 1

#228 [PLA-1943] Fix relationship total count
  src/GraphQL/Schemas/Primary/Substrate/Queries/GetCollectionsQuery.php
  tests/Feature/GraphQL/Queries/GetCollectionsTest.php
Labels: tests, Review effort [1-5]: 3, Bug fix

#274 [Hotfix] Accept any gmajor version
  composer.json
Labels: enhancement, Review effort [1-5]: 1

#275 [PLA-2026] Add support for infused at ingest
  src/Enums/Substrate/MultiTokensEventType.php
  src/Events/Substrate/MultiTokens/TokenInfused.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Infused.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Infused.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenMutated.php
Labels: enhancement, Review effort [1-5]: 3

#276 [PLA-2023] Sync attribute when creating or updating
  src/Models/Laravel/Attribute.php
Labels: enhancement, Review effort [1-5]: 2

#273 [PLA-2045] Improve query performance
  database/factories/TransactionFactory.php
  database/migrations/2024_10_17_061240_add_managed_to_transactions_table.php
  src/CoreServiceProvider.php
  src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
  src/Models/Laravel/Transaction.php
  src/Support/Account.php
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#277 [PLA-2023] Remove without verifying
  src/Clients/Abstracts/HttpAbstract.php
Labels: enhancement, Review effort [1-5]: 1

#278 [PLA-2023] Make function for easy override
  src/Commands/SyncMetadata.php
Labels: enhancement, Review effort [1-5]: 2

#280 [PLA-2026] Get new fields from Extrinsic for CreateToken
  src/Services/Processor/Substrate/Codec/Polkadart/Extrinsics/MultiTokens/Mint.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
Labels: Review effort [1-5]: 3

#279 [PLA-2023] Refactor constant
  database/factories/PendingEventFactory.php
  src/Commands/SyncMetadata.php
  src/Models/Laravel/Attribute.php
  src/Services/Database/MetadataService.php
  tests/Feature/GraphQL/Queries/GetPendingEventsTest.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
Labels: enhancement, Review effort [1-5]: 2, tests

#281 [PLA-2054] Fix batch mint utility
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
Labels: Review effort [1-5]: 2

#282 [PLA-2057] Fix RemoveAccountRuleData codec
  src/Services/Processor/Substrate/Codec/Types/RemoveAccountRuleData.json
Labels: Review effort [1-5]: 1

#283 [PLA-2058] Add anyone can infuse
  src/GraphQL/Schemas/Primary/Substrate/Mutations/MutateTokenMutation.php
  src/GraphQL/Types/Input/Substrate/TokenMutationInputType.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
Labels: Review effort [1-5]: 3

#284 [PLA-2062] Remove google qr adapter
  src/Services/Qr/Adapters/GoogleQrAdapter.php
Labels: Review effort [1-5]: 1
