Repository enjin/platform-core, pull requests merged in 2024-06, with the labels that each got.

#176 [PLA-1806] Attributes duplicated fix + Adds model to some events
  database/factories/AttributeFactory.php
  database/migrations/2024_06_05_113420_alter_attributes_table.php
  src/Commands/RelayWatcher.php
  src/CoreServiceProvider.php
  src/Events/Global/TransactionCreated.php
  src/Events/Global/TransactionUpdated.php
  src/Events/PlatformBroadcastEvent.php
  src/Events/Substrate/MultiTokens/CollectionCreated.php
  src/Events/Substrate/MultiTokens/TokenCreated.php
  src/Events/Substrate/MultiTokens/TokenMinted.php
  src/GraphQL/Types/Substrate/AttributeType.php
  src/Models/Laravel/Attribute.php
  src/Services/Database/TransactionService.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
  src/Services/Processor/Substrate/Parser.php
  testbench.yaml
  tests/Feature/GraphQL/Queries/GetCollectionTest.php
  tests/Feature/GraphQL/Queries/GetCollectionsTest.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
  tests/Feature/GraphQL/Queries/GetTokensTest.php
  tests/Feature/GraphQL/Queries/GetWalletTest.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#177 [PLA-1806] Fixes wrong var
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#179 [PLA-1855] Fixes for hex encoded attribute keys and values.
  src/Services/Database/TokenService.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeSet.php
Labels: Review effort [1-5]: 2, Bug fix

#181 [PLA-1806] Attributes primary key fixes
  database/factories/AttributeFactory.php
  database/migrations/2024_06_05_113420_alter_attributes_table.php
  src/CoreServiceProvider.php
  src/GraphQL/Types/Substrate/AttributeType.php
  src/Models/Laravel/Attribute.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeSet.php
  src/Services/Processor/Substrate/Parser.php
  testbench.yaml
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Queries/GetCollectionTest.php
  tests/Feature/GraphQL/Queries/GetCollectionsTest.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
  tests/Feature/GraphQL/Queries/GetTokensTest.php
  tests/Feature/GraphQL/Queries/GetWalletTest.php
Labels: bug, enhancement, Review effort [1-5]: 3, Bug fix

#183 [PLA-1851] Fix missing FuelTank events
  src/Services/Processor/Substrate/ExtrinsicProcessor.php
Labels: bug

#184 [PLA-1851] Fixes FuelTank events
  src/Services/Processor/Substrate/ExtrinsicProcessor.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#178 [PLA-1806] Class init error
  src/Commands/RelayWatcher.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/AttributeRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Unapproved.php
Labels: Review effort [1-5]: 2, Bug fix

#187 [PLA-1838] Fixes token freeze with nullable freezeState
  src/GraphQL/Schemas/Primary/Substrate/Mutations/FreezeMutation.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Unit/EncodingTest.php
Labels: bug, Review effort [1-5]: 2, tests, Bug fix

#185 [PLA-1678] Laravel 11 Update.
  .github/workflows/run_tests.yml
  composer.json
  phpunit.xml
  src/Models/Laravel/Collection.php
  src/Models/Laravel/CollectionAccount.php
  src/Models/Laravel/Event.php
  src/Models/Laravel/Token.php
  src/Models/Laravel/TokenAccount.php
  testbench.yaml
Labels: enhancement, dependencies, Review effort [1-5]: 2

#190 [PLA-1867] Upgrades amphp libs
  composer.json
  src/Clients/Implementations/AsyncWebsocket.php
  src/Commands/Sync.php
  testbench.yaml
Labels: enhancement, dependencies, Review effort [1-5]: 4, Bug fix

#191 [PLA-1693] Improved local testing tweaks.
  src/Package.php
Labels: enhancement, Review effort [1-5]: 2
