Repository enjin/platform-core, pull requests merged in 2024-09, with the labels that each got.

#234 [PLA-1974] Add return null
  src/Services/Processor/Substrate/DecoderService.php
Labels: bug_fix, Review effort [1-5]: 1

#235 [PLA-1978] MultiMetadata support
  config/enjin-runtime.php
  src/Commands/RelayWatcher.php
  src/CoreServiceProvider.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/Processor.php
  src/Support/helpers.php
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#236 Lower decoder retry to 3
  src/Services/Processor/Substrate/BlockProcessor.php
Labels: enhancement, Review effort [1-5]: 2

#237 [PLA-1979] Throw exception on invalid encoded data
  src/Services/Processor/Substrate/Codec/Encoder.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#239 [PLA-1982] Upgrade runtime & specs for mainnet
  config/enjin-platform.php
  config/enjin-runtime.php
Labels: Review effort [1-5]: 1, Configuration changes

#241 [PLA-1984] Move IntegerRangeString scalar
  lang/en/type.php
  src/GraphQL/Types/Scalars/IntegerRangeStringType.php
Labels: documentation, enhancement, Review effort [1-5]: 3

#242 [PLA-1985] Allow update with same hash on UpdateTransaction
  src/Rules/ImmutableTransaction.php
  tests/Feature/GraphQL/Mutations/UpdateTransactionTest.php
Labels: Review effort [1-5]: 2, bug_fix

#243 [PLA-1986] Fixes storage parsing during migration
  src/Services/Processor/Substrate/Codec/Decoder.php
Labels: Review effort [1-5]: 2, Bug fix

#245 [PLA-1990] Fixes marketplace prices
  src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
Labels: enhancement, Review effort [1-5]: 2

#244 [PLA-1986] Removes decoder migration fix
  composer.json
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Support/Metadata.php
  tests/Feature/Controllers/QrControllerTest.php
  tests/Feature/GraphQL/Mutations/AddToTrackedTest.php
  tests/Feature/GraphQL/Mutations/VerifyAccountTest.php
  tests/Feature/GraphQL/Queries/VerifyMessageTest.php
  tests/Unit/StorageTest.php
Labels: enhancement, Review effort [1-5]: 2

#248 [PLA-1998] Deprecate keepAlive from OperatorTransferToken
  lang/en/deprecated.php
  lang/en/mutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/OperatorTransferTokenMutation.php
  src/GraphQL/Types/Input/Substrate/OperatorTransferParamsInputType.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
Labels: documentation, enhancement, Review effort [1-5]: 2

#251 Adds deprecationReason to keepAlive & TransferBalance
  lang/en/deprecated.php
  lang/en/mutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/TransferBalanceMutation.php
  src/GraphQL/Types/Input/Substrate/OperatorTransferParamsInputType.php
  src/GraphQL/Types/Input/Substrate/SimpleTransferParamsInputType.php
Labels: documentation, enhancement, Review effort [1-5]: 2

#252 [PLA-2004] Forget customTypes when ingest starts
  src/Services/Processor/Substrate/BlockProcessor.php
Labels: enhancement, Review effort [1-5]: 2

#253 [PLA-2006] Add new args to CreateToken mutation
  lang/en/deprecated.php
  lang/en/input_type.php
  src/GraphQL/Types/Input/Substrate/CreateTokenParamsInputType.php
  src/GraphQL/Types/Input/Substrate/MetadataInputType.php
  src/Models/Substrate/CreateTokenParams.php
  src/Models/Substrate/MetadataParams.php
  src/Models/Substrate/TokenMarketBehaviorParams.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Types/Mint.json
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Unit/Decoder/MintTest.php
  tests/Unit/DecodingTest.php
  tests/Unit/Encoder/MintTest.php
  tests/Unit/EncodingTest.php
Labels: enhancement, tests, Review effort [1-5]: 4

#254 [PLA-2014] Adds SubstrateHttpClient for fetching balance
  src/Clients/Implementations/AsyncSocketClient.php
  src/Clients/Implementations/DecoderHttpClient.php
  src/Clients/Implementations/MetadataHttpClient.php
  src/Clients/Implementations/SubstrateHttpClient.php
  src/Clients/Implementations/SubstrateSocketClient.php
  src/Commands/RelayWatcher.php
  src/Commands/Sync.php
  src/Commands/Transactions.php
  src/Commands/contexts/get_extrinsics.php
  src/Commands/contexts/get_storage.php
  src/Providers/Deferred/WebsocketClientProvider.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Database/MetadataService.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/ExtrinsicProcessor.php
  src/Services/Processor/Substrate/State.php
  tests/Feature/GraphQL/Mutations/AcceptCollectionTransferTest.php
  tests/Feature/GraphQL/Mutations/ApproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchMintTest.php
  tests/Feature/GraphQL/Mutations/BatchSetAttributeTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferBalanceTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
  tests/Feature/GraphQL/Mutations/DestroyCollectionTest.php
  tests/Feature/GraphQL/Mutations/FreezeTest.php
  tests/Feature/GraphQL/Mutations/MintTokenTest.php
  tests/Feature/GraphQL/Mutations/MutateCollectionTest.php
  tests/Feature/GraphQL/Mutations/MutateTokenTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SendTransactionTest.php
  tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/ThawTest.php
  tests/Feature/GraphQL/Mutations/TransferAllBalanceTest.php
  tests/Feature/GraphQL/Mutations/TransferAllowDeathTest.php
  tests/Feature/GraphQL/Mutations/TransferKeepAliveTest.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
  tests/Feature/GraphQL/Queries/GetWalletAuthTest.php
  tests/Feature/GraphQL/Queries/GetWalletTest.php
  tests/Feature/GraphQL/Queries/GetWalletsTest.php
  tests/Support/Mocks/StorageMock.php
  tests/Support/MocksHttpClient.php
  tests/Support/MocksSocketClient.php
  tests/Unit/DepositFeeTest.php
  tests/Unit/WalletTest.php
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#256 [PLA-2016] Use Dependency Injection for DecoderService
  src/Commands/RelayWatcher.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/Processor.php
  src/Services/Processor/Substrate/State.php
Labels: enhancement, Review effort [1-5]: 3

#255 [PLA-2015] Improve syncable tracking.
  lang/en/error.php
  src/GraphQL/Enums/TransactionMethodEnum.php
  src/GraphQL/Schemas/Primary/Mutations/AddToTrackedMutation.php
  src/GraphQL/Schemas/Primary/Mutations/RemoveFromTrackedMutation.php
  src/Services/Database/CollectionService.php
  src/Services/Database/SyncableService.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Events/SubstrateEvent.php
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#257 [PLA-2017] Fix total count cache key
  src/CoreServiceProvider.php
Labels: bug, Review effort [1-5]: 2, Bug fix
