Repository enjin/platform-core, pull requests merged in 2024-04, with the labels that each got.

#150 [PLA-1692] Support channel filters in GetPendingEvents.
  lang/en/type.php
  src/Enums/Global/FilterType.php
  src/GraphQL/Enums/FilterTypeEnum.php
  src/GraphQL/Schemas/Primary/Queries/GetPendingEventsQuery.php
  src/GraphQL/Types/Input/Global/StringFilterInputType.php
  tests/Feature/GraphQL/Queries/GetPendingEventsTest.php
  tests/Feature/GraphQL/Resources/GetPendingEvents.graphql
Labels: enhancement, Review effort [1-5]: 3

#151 [Hotfix] Issue with BatchTransferBalance on Fuel-Tanks package
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferBalanceMutation.php
Labels: bug, enhancement, Review effort [1-5]: 1

#152 [PLA-1706] Fixes fuelTank event argument
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FreezeStateMutated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#149 [PLA-1685] Add model owner attribute
  src/Models/BaseModel.php
  src/Models/Laravel/Token.php
Labels: enhancement, Review effort [1-5]: 3

#153 [PLA-1706] Decoder changes for marketplace
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingFilled.php
Labels: enhancement, Review effort [1-5]: 2

#154 [PLA-1720] Support for force_mint.
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
Labels: enhancement, Review effort [1-5]: 2

#155 [PLA-1721] Retry RPC request on sync
  src/Commands/Sync.php
  src/Commands/contexts/get_storage.php
Labels: bug, Review effort [1-5]: 2, bug_fix

#156 [PLA-1723][PLA-1724] Fixes CollectionMutated & TokenReserved websocket event
  src/Events/Substrate/MultiTokens/TokenReserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
Labels: bug, enhancement, bug_fix, Review effort [1-5]: 3

#157 [PLA-1726] Fixes TokenUnreserved websocket event
  src/Events/Substrate/MultiTokens/TokenUnreserved.php
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#158 [PLA-1729] Adds CollectionTransferred event
  src/Enums/Substrate/MultiTokensEventType.php
  src/Events/Substrate/MultiTokens/CollectionTransferred.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionTransferred.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionTransferred.php
Labels: enhancement, Review effort [1-5]: 3

#159 [PLA-1739] Return a 400 status code if the GraphQL response contains errors.
  src/Http/Controllers/GraphQLController.php
Labels: Review effort [1-5]: 2, bug_fix
