Repository enjin/platform-core, pull requests merged in 2024-03, with the labels that each got.

#138 [PLA-1608] Token metadata fallback, and {id} replacement.
  src/GraphQL/Types/Substrate/AttributeType.php
  src/Models/Laravel/Block.php
  src/Models/Laravel/Token.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
Labels: enhancement, Review effort [1-5]: 3

#139 [PLA-1681] Bump transactionVersion and specVersion
  config/enjin-platform.php
Labels: enhancement, Review effort [1-5]: 1

#142 [PLA-1696] Remove scopes for rules in service classes.
  src/Services/Database/CollectionService.php
  src/Services/Database/TokenService.php
  src/Services/Database/WalletService.php
Labels: Review effort [1-5]: 2, bug_fix

#144 [PLA-1700] Add API generic rate limit
  config/enjin-platform.php
  src/Http/Controllers/GraphQLController.php
  testbench.yaml
  tests/Feature/GraphQL/Middleware/RateLimit.php
Labels: enhancement, Review effort [1-5]: 3

#143 [PLA-1690] Add transaction hash to event data
  src/Events/Substrate/Balances/Transfer.php
Labels: enhancement, Review effort [1-5]: 1

#140 [PLA-1684] Fix sql query
  src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
Labels: Review effort [1-5]: 2, bug_fix

#146 [PLA-1704] Add WhitelistedPallets codec
  src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json
  src/Services/Processor/Substrate/Codec/Types/TankStorage.json
Labels: enhancement, Review effort [1-5]: 1
