Repository enjin/platform-core, pull requests merged in 2024-05, with the labels that each got.

#162 [PLA-1747] Fix prune pending event
  config/enjin-platform.php
  src/Models/Laravel/PendingEvent.php
  tests/Feature/Commands/PruneTest.php
Labels: bug, Review effort [1-5]: 2, bug_fix, tests

#163 [PLA-1751] Add retries for decoder
  src/Clients/Abstracts/HttpAbstract.php
  src/Services/Processor/Substrate/BlockProcessor.php
Labels: enhancement, Review effort [1-5]: 3

#165 [PLA-1754] Change specVersion for Matrix Canary
  config/enjin-platform.php
Labels: enhancement, Review effort [1-5]: 1

#166 [PLA-1755] Fixes burn mutation validation
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php
  tests/Feature/GraphQL/Mutations/BurnTest.php
Labels: bug, enhancement, tests, Review effort [1-5]: 3, Bug fix

#164 [PLA-1730] Adds acceptCollectionTransfer
  database/factories/CollectionFactory.php
  database/migrations/2024_05_06_100918_add_pending_transfer_collections_table.php
  lang/en/mutation.php
  lang/en/validation.php
  src/Commands/Sync.php
  src/Enums/Substrate/StorageKey.php
  src/Enums/Substrate/StorageType.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/AcceptCollectionTransferMutation.php
  src/Models/Laravel/Collection.php
  src/Rules/AccountWaitingCollectionTransfer.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/Codec/Types/AcceptCollectionTransfer.json
  src/Services/Processor/Substrate/Codec/Types/PendingCollectionTransfersStorage.json
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionTransferred.php
  src/Services/Processor/Substrate/Parser.php
  src/Support/Metadata.php
  tests/Feature/GraphQL/Mutations/AcceptCollectionTransferTest.php
  tests/Feature/GraphQL/Resources/AcceptCollectionTransfer.graphql
Labels: enhancement, tests, Review effort [1-5]: 4

#167 [PLA-1757] Fixes hex FuelTanks name
  src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php
Labels: bug, Review effort [1-5]: 2, bug_fix

#168 Bump matrix to v1006
  config/enjin-platform.php
Labels: enhancement, Review effort [1-5]: 1

#141 [PLA-1455] Watch relaychain deposits in managed wallet
  config/enjin-platform.php
  database/migrations/2024_03_18_184722_add_network_field_in_transactions_table.php
  src/Clients/Implementations/AsyncWebsocket.php
  src/Clients/Implementations/SubstrateWebsocket.php
  src/Commands/RelayWatcher.php
  src/Commands/Sync.php
  src/CoreServiceProvider.php
  src/Enums/Global/ChainType.php
  src/Enums/Global/NetworkType.php
  src/Enums/Global/PlatformCache.php
  src/GraphQL/Enums/NetworkTypeEnum.php
  src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Queries/GetWalletsQuery.php
  src/GraphQL/Types/Substrate/TransactionType.php
  src/Http/Controllers/PlatformController.php
  src/Models/Laravel/Transaction.php
  src/Providers/Deferred/BlockchainServiceProvider.php
  src/Providers/Deferred/SerializationServiceProvider.php
  src/Providers/Deferred/WebsocketClientProvider.php
  src/Providers/GraphQlServiceProvider.php
  src/Services/Database/TransactionService.php
  src/Services/Database/VerificationService.php
  src/Services/Processor/Substrate/Codec/Decoder.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Support/helpers.php
  testbench.yaml
  tests/Feature/Controllers/PlatformControllerTest.php
Labels: enhancement, other, Review effort [1-5]: 4

#169 [PLA-1767] Increases attribute validation size
  lang/en/validation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetCollectionAttributeMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SetTokenAttributeMutation.php
  src/GraphQL/Types/Input/Substrate/AttributeInputType.php
  src/Rules/StringMaxByteLength.php
  tests/Feature/GraphQL/Mutations/CreateCollectionTest.php
  tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php
  tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
Labels: enhancement, tests, Review effort [1-5]: 3

#170 [PLA-1769] Fire transaction created event on relay watcher
  src/Commands/RelayWatcher.php
Labels: enhancement, Review effort [1-5]: 2

#171 [PLA-1770] Adds Balances.Teleport + LimitedTeleportAssets method.
  src/Commands/RelayWatcher.php
  src/Enums/Substrate/XcmOutcome.php
  src/Events/Substrate/Balances/Teleport.php
  src/GraphQL/Enums/TransactionMethodEnum.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/XcmPallet/Attempted.php
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#173 [PLA-1777] Resolve pagination issue
  src/GraphQL/Schemas/Primary/Substrate/Queries/GetWalletsQuery.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#175 [Hotfix] Fixes platform:sync on SYNC_ALL
  src/Commands/Sync.php
Labels: bug, Review effort [1-5]: 2
