Repository enjin/platform-core, pull requests merged in 2024-11, with the labels that each got.

#285 [PLA-1975] Add custom queue
  config/enjin-platform.php
  src/Events/Global/TransactionCreated.php
  src/Events/Global/TransactionUpdated.php
  src/Events/PlatformBroadcastEvent.php
  src/Events/PlatformEvent.php
  src/Events/Substrate/Balances/BalanceSet.php
  src/Events/Substrate/Balances/Deposit.php
  src/Events/Substrate/Balances/DustLost.php
  src/Events/Substrate/Balances/Endowed.php
  src/Events/Substrate/Balances/ReserveRepatriated.php
  src/Events/Substrate/Balances/Reserved.php
  src/Events/Substrate/Balances/Slashed.php
  src/Events/Substrate/Balances/Teleport.php
  src/Events/Substrate/Balances/Transfer.php
  src/Events/Substrate/Balances/Unreserved.php
  src/Events/Substrate/Balances/Withdraw.php
  src/Events/Substrate/Commands/PlatformBlockIngested.php
  src/Events/Substrate/Commands/PlatformBlockIngesting.php
  src/Events/Substrate/Commands/PlatformEventCached.php
  src/Events/Substrate/Commands/PlatformSyncError.php
  src/Events/Substrate/Commands/PlatformSynced.php
  src/Events/Substrate/Commands/PlatformSyncing.php
  src/Events/Substrate/MultiTokens/CollectionAccountCreated.php
  src/Events/Substrate/MultiTokens/CollectionAccountDestroyed.php
  src/Events/Substrate/MultiTokens/CollectionAccountFrozen.php
  src/Events/Substrate/MultiTokens/CollectionAccountThawed.php
  src/Events/Substrate/MultiTokens/CollectionApproved.php
  src/Events/Substrate/MultiTokens/CollectionAttributeRemoved.php
  src/Events/Substrate/MultiTokens/CollectionAttributeSet.php
  src/Events/Substrate/MultiTokens/CollectionCreated.php
  src/Events/Substrate/MultiTokens/CollectionDestroyed.php
  src/Events/Substrate/MultiTokens/CollectionFrozen.php
  src/Events/Substrate/MultiTokens/CollectionMutated.php
  src/Events/Substrate/MultiTokens/CollectionThawed.php
  src/Events/Substrate/MultiTokens/CollectionTransferred.php
  src/Events/Substrate/MultiTokens/CollectionUnapproved.php
  src/Events/Substrate/MultiTokens/MetadataUpdated.php
  src/Events/Substrate/MultiTokens/TokenAccountCreated.php
  src/Events/Substrate/MultiTokens/TokenAccountDestroyed.php
  src/Events/Substrate/MultiTokens/TokenAccountFrozen.php
  src/Events/Substrate/MultiTokens/TokenAccountThawed.php
  src/Events/Substrate/MultiTokens/TokenApproved.php
  src/Events/Substrate/MultiTokens/TokenAttributeRemoved.php
  src/Events/Substrate/MultiTokens/TokenAttributeSet.php
  src/Events/Substrate/MultiTokens/TokenBurned.php
  src/Events/Substrate/MultiTokens/TokenCreated.php
  src/Events/Substrate/MultiTokens/TokenDestroyed.php
  src/Events/Substrate/MultiTokens/TokenFrozen.php
  src/Events/Substrate/MultiTokens/TokenInfused.php
  src/Events/Substrate/MultiTokens/TokenMinted.php
  src/Events/Substrate/MultiTokens/TokenMutated.php
  src/Events/Substrate/MultiTokens/TokenReserved.php
  src/Events/Substrate/MultiTokens/TokenThawed.php
  src/Events/Substrate/MultiTokens/TokenTransferred.php
  src/Events/Substrate/MultiTokens/TokenUnapproved.php
  src/Events/Substrate/MultiTokens/TokenUnreserved.php
  src/Jobs/HotSync.php
  src/Jobs/ParseChainData.php
  src/Jobs/SyncMetadata.php
  src/Traits/HasCustomQueue.php
Labels: Review effort [1-5]: 3

#286 [PLA-2068] Fix event should go to public key channels
  src/Events/Global/TransactionCreated.php
  src/Events/Global/TransactionUpdated.php
Labels: Review effort [1-5]: 2

#288 [PLA-2088] Fix collapsing supply
  src/Services/Blockchain/Implementations/Substrate.php
  tests/Feature/GraphQL/Mutations/CreateTokenTest.php
Labels: Review effort [1-5]: 2

#290 [PLA-1946] Fix translation
  lang/en/validation.php
Labels: Review effort [1-5]: 1
