Repository enjin/platform-core, pull requests merged in 2024-01, with the labels that each got.

#114 [PLA-1210] Adds collection filter to sync&ingest
  src/Commands/Sync.php
  src/Commands/TransactionChecker.php
  src/Enums/Substrate/StorageKey.php
  src/Enums/Substrate/StorageType.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  src/Services/Processor/Substrate/EventProcessor.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Approved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeRemoved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeSet.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionAccountCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionAccountDestroyed.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionDestroyed.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Freeze.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Reserved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Thawed.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenAccountCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenAccountDestroyed.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenBurned.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenDestroyed.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenMutated.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Transferred.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Unapproved.php
  src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Unreserved.php
  src/Services/Processor/Substrate/Events/Implementations/Traits/QueryDataOrFail.php
  src/Services/Processor/Substrate/ExtrinsicProcessor.php
Labels: enhancement

#115 [PLA-1522] Adds SendTransaction mutation
  lang/en/error.php
  src/GraphQL/Schemas/Primary/Mutations/SendTransactionMutation.php
  src/Providers/Faker/SubstrateProvider.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/Codec/Encoder.php
  tests/Feature/GraphQL/Mutations/SendTransactionTest.php
  tests/Feature/GraphQL/Resources/SendTransaction.graphql
Labels: enhancement

#117 [PLA-1533] Change SigningPayloadJSON format for Enjin Wallet
  src/Services/Processor/Substrate/Codec/Encoder.php
Labels: bug

#120 [PLA-1537] Add filter to marketplace & fueltanks
  src/Commands/Sync.php
Labels: enhancement

#121 [PLA-1541] Appends schema to primary instead of overwrite
  src/Providers/GraphQlServiceProvider.php
Labels: bug

#119 [PLA-1526] Remove wallet daemon query
  src/Rules/ApprovalExistsInCollection.php
  tests/Feature/GraphQL/Mutations/UnapproveCollectionTest.php
Labels: bug

#123 [PLA-1547] Fixes transactions from a new managed wallet not being returned
  src/Observers/WalletObserver.php
  src/Support/Account.php
Labels: bug

#124 [PLA-1557] Prevent update FINALIZED state
  src/GraphQL/Schemas/Primary/Substrate/Mutations/RetryTransactionsMutation.php
  tests/Feature/GraphQL/Mutations/RetryTransactionsTest.php
Labels: bug

#125 [PLA-1560] Prevent retry on FINALIZED transaction
  lang/en/error.php
  src/GraphQL/Schemas/Primary/Mutations/UpdateTransactionMutation.php
  tests/Feature/GraphQL/Mutations/UpdateTransactionTest.php
Labels: bug

#127 [PLA-1448] Adds balances pallet events
  src/Enums/Substrate/BalancesEventType.php
  src/Events/Substrate/Balances/BalanceSet.php
  src/Events/Substrate/Balances/Deposit.php
  src/Events/Substrate/Balances/DustLost.php
  src/Events/Substrate/Balances/Endowed.php
  src/Events/Substrate/Balances/ReserveRepatriated.php
  src/Events/Substrate/Balances/Reserved.php
  src/Events/Substrate/Balances/Slashed.php
  src/Events/Substrate/Balances/Transfer.php
  src/Events/Substrate/Balances/Unreserved.php
  src/Events/Substrate/Balances/Withdraw.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/BalanceSet.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Deposit.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/DustLost.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Endowed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/ReserveRepatriated.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Reserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Slashed.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Transfer.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Unreserved.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/Balances/Withdraw.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/BalanceSet.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Deposit.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/DustLost.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Endowed.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/ReserveRepatriated.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Reserved.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Slashed.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Transfer.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Unreserved.php
  src/Services/Processor/Substrate/Events/Implementations/Balances/Withdraw.php
Labels: enhancement

#128 [PLA-1559] Use model for scoping
  src/GraphQL/Schemas/Primary/Mutations/SetWalletAccountMutation.php
  src/GraphQL/Schemas/Primary/Mutations/UpdateWalletExternalIdMutation.php
  src/GraphQL/Schemas/Primary/Queries/GetPendingWalletsQuery.php
  src/Models/Laravel/Wallet.php
Labels: enhancement, Review effort [1-5]: 2
