Repository enjin/platform-core, pull requests merged in 2025-01, with the labels that each got.

#292 [PLA-2095] Add telemetry
  config/telemetry.php
  database/migrations/2024_11_26_011849_create_settings_table.php
  src/Commands/SendTelemetryEvent.php
  src/CoreServiceProvider.php
  src/Enums/Global/PlatformCache.php
  src/Enums/Global/SettingsEnum.php
  src/Enums/TelemetrySource.php
  src/Http/Middleware/Telemetry.php
  src/Services/PhoneHomeService.php
Labels: Review effort [1-5]: 3

#291 [PLA-2098] Update qr code styling
  config/enjin-platform.php
  src/Http/Controllers/QrController.php
Labels: Review effort [1-5]: 2

#308 [PLA-2126] Upgrade dependencies
  composer.json
  lang/en/enum.php
  lang/en/input_type.php
  scripts/generate-schema.sh
  tests/Feature/GraphQL/Types/TestType.php
Labels: Review effort [1-5]: 3

#309 [PLA-2095] Update provider configuration
  src/CoreServiceProvider.php
Labels: Review effort [1-5]: 2

#310 [PLA-2125] Add helper function
  src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
Labels: Review effort [1-5]: 2

#311 [PLA-2127] Fix validation for token exist
  src/Rules/TokenEncodeExists.php
  tests/Feature/GraphQL/Queries/GetTokenTest.php
Labels: Review effort [1-5]: 3

#293 [PLA-2091] Add wallet created event
  src/Events/Global/WalletCreated.php
  src/Observers/WalletObserver.php
Labels: Review effort [1-5]: 2

#312 [PLA-2125] Fix calling helper in static function
  src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
Labels: Review effort [1-5]: 3

#313 [PLA-2125] Refactor expandRanges function
  src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
  tests/Feature/Controllers/QrControllerTest.php
  tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
  tests/Feature/GraphQL/Mutations/BatchTransferTest.php
  tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
  tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
  tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
  tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php
Labels: Review effort [1-5]: 2

#314 [PLA-2128] Adds new metadata v1014
  config/enjin-platform.php
  config/enjin-runtime.php
Labels: Review effort [1-5]: 2

#316 [PLA-1761] Runtime upgrade
  composer.json
  config/enjin-platform.php
  src/Enums/Global/PlatformCache.php
  src/Enums/Substrate/SystemEventType.php
  src/Events/Substrate/System/CodeUpdated.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Codec/Polkadart/Events/System/CodeUpdated.php
  src/Services/Processor/Substrate/DecoderService.php
  src/Services/Processor/Substrate/Events/Implementations/System/CodeUpdated.php
  src/Services/Processor/Substrate/State.php
  src/Support/Util.php
  src/Support/helpers.php
  tests/TestCase.php
Labels: Review effort [1-5]: 4

#318 [PLA-2111] Add token holder snapshot API
  config/enjin-platform.php
  lang/en/error.php
  lang/en/mutation.php
  src/GraphQL/Schemas/Primary/Mutations/TokenHolderSnapshotMutation.php
  tests/Feature/GraphQL/Mutations/TokenHolderSnapshotTest.php
  tests/Feature/GraphQL/Resources/TokenHolderSnapshot.graphql
Labels: Review effort [1-5]: 4

#319 [PLA-2151] Fixes relay watcher
  config/enjin-platform.php
  src/Commands/RelayWatcher.php
  src/Commands/Sync.php
  src/GraphQL/Types/Scalars/DateTimeType.php
  src/Services/Blockchain/Implementations/Substrate.php
  src/Services/Processor/Substrate/BlockProcessor.php
  src/Services/Processor/Substrate/Events/Implementations/System/CodeUpdated.php
  src/Support/Util.php
  src/Support/helpers.php
  tests/TestCase.php
Labels: Review effort [1-5]: 4

#320 [PLA-2154] Block processor issue
  src/Services/Processor/Substrate/BlockProcessor.php
Labels: Review effort [1-5]: 2

#322 [PLA-2157] Fixes transfer validation rules
  .github/workflows/linter.yml
  .github/workflows/pr_agent.yml
  .github/workflows/run_tests.yml
  .github/workflows/sast.yml
  .github/workflows/security_checker.yml
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/OperatorTransferTokenMutation.php
  src/GraphQL/Schemas/Primary/Substrate/Mutations/SimpleTransferTokenMutation.php
Labels: Review effort [1-5]: 4

#321 [PLA-2111] Fix email content
  src/GraphQL/Schemas/Primary/Mutations/TokenHolderSnapshotMutation.php
Labels: Review effort [1-5]: 2
